"""migrations_init

Revision ID: 4b2468a868e3
Revises: 
Create Date: 2024-05-25 21:21:26.045569

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b2468a868e3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings_profiles",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("wait_seconds", sa.Integer(), nullable=False),
        sa.Column("path_to_gpg", sa.String(), nullable=False),
        sa.Column("path_to_external_gpg", sa.String(), nullable=False),
        sa.Column("path_to_stored_passwords", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings_profiles")
    # ### end Alembic commands ###
